name: foore
description: Foore mobile app

version: 0.1.1+74

environment:
  sdk: '>=2.5.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  after_layout: ^1.0.7+2

  intl: ^0.16.1

  http: ^0.12.0+2

  rxdart: ^0.22.2

  provider: ^3.1.0

  shared_preferences: ^0.5.3+4

  firebase_messaging: ^7.0.0

  google_sign_in: ^4.5.3

  url_launcher: ^5.5.3

  carousel_slider: ^1.3.1

  intercom_flutter: ^2.2.0+1

  package_info: ">=0.4.0 <2.0.0"


  firebase_analytics: ^6.0.0

  google_maps_flutter: ^0.5.21+11

  sprintf: ^4.0.2

  contacts_service: ^0.4.6

  permission_handler: ^4.0.0

  #flare_flutter: ^1.7.3

  rake: ^1.0.1

  image_picker: ^0.6.7+2

  geolocator: 5.2.0

  uuid: 2.1.0
  fluttertoast: ^7.0.4
  sentry: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo-black.png
    - assets/es-logo.png
    - assets/es-logo-small.png
    - assets/googlelogo.png
    - assets/google-icon.png
    - assets/messengerlogo.png
    - assets/button-click.png
    - assets/growth.png
    - assets/empty-state.png
    - assets/whatsapp.png
    - assets/hindi-share.png
    - assets/english-share.png
    - assets/sms-code.png
    - assets/promotion-banner.png
    - assets/locale/localization_hi.json
    - assets/locale/localization_kn.json
    - assets/locale/localization_ml.json
    - assets/locale/localization_mr.json
    - assets/locale/localization_ta.json
    - assets/locale/localization_te.json
    - assets/locale/localization_pa.json
    - assets/locale/localization_en.json
    - assets/locale/localization_gu.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-Regular.ttf
