name: foore
description: Foore mobile app

version: 0.5.3+112

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2

  after_layout: ^1.0.7+2

  intl: ^0.16.1

  http: ^0.12.0+2

  rxdart: ^0.22.2

  provider: ^3.1.0

  shared_preferences: ^0.5.3+4

  firebase_messaging: ^7.0.0

  google_sign_in: ^4.5.4

  url_launcher: ^5.5.3

  carousel_slider: ^1.3.1

  package_info: ">=0.4.0 <2.0.0"

  firebase_analytics: ^6.0.0

  sprintf: ^4.0.2

  contacts_service: ^0.4.6

  permission_handler: ^4.0.0

  rake: ^1.0.1

  image_picker: ^0.6.7+2

  geolocator: ^6.1.6

  uuid: ^2.2.2

  fluttertoast: ^7.0.4

  flutter_local_notifications: ^1.4.4+4

  video_player: ^0.10.12+3

  cached_network_image:

  chewie: ^0.9.10
  firebase_dynamic_links: ^0.6.0+1
  esys_flutter_share: ^1.0.2

  firebase_crashlytics: ^0.2.2

  firebase_core: ^0.5.0+1

  image_cropper: ^1.3.1

  geocoder: ^0.2.1

  google_maps_webservice: ^0.0.18

  google_maps_flutter: ^1.0.6

  flutter_typeahead: ^2.0.0

  esamudaay_app_update:
    git:
      url: https://anushka_agrawal@bitbucket.org/ese1/esm_comp_appupdate.git
      ref: v0.0.1

  esamudaay_themes:
    git:
      url: https://anushka_agrawal@bitbucket.org/ese1/esm_comp_themes.git
      ref: v0.0.1

  app_settings: ^4.0.4

  circles:
    git:
      url: https://kaustubh-pandey@bitbucket.org/ese1/esm_comp_circle.git

dependency_overrides:
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo-black.png
    - assets/es-logo.png
    - assets/es-logo-small.png
    - assets/googlelogo.png
    - assets/google-icon.png
    - assets/messengerlogo.png
    - assets/button-click.png
    - assets/growth.png
    - assets/empty-state.png
    - assets/whatsapp.png
    - assets/hindi-share.png
    - assets/english-share.png
    - assets/sms-code.png
    - assets/promotion-banner.png
    - assets/circle_tile_placeholder.png
    - assets/location-pointer.png
    - assets/category_placeholder.png
    
    - assets/icons/categories.png
    - assets/icons/list-view.png
    - assets/icons/spotlights.png
    - assets/icons/out-of-stock.png
    - assets/icons/sort.png
    
    - assets/locale/localization_hi.json
    - assets/locale/localization_kn.json
    # - assets/locale/localization_ml.json
    # - assets/locale/localization_mr.json
    - assets/locale/localization_ta.json
    - assets/locale/localization_te.json
    # - assets/locale/localization_pa.json
    - assets/locale/localization_en.json
    # - assets/locale/localization_gu.json
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Black.ttf
        - asset: fonts/Lato-Italic.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-Regular.ttf
